name: Continuous Integration

on:
  push:
    branches: ['main', 'dev', 'feature/**', 'automations']
  pull_request:
    branches: ['main', 'dev']

permissions:
  contents: read

jobs:
  test:
    name: pytest (py${{ matrix.python-version }} • ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install project with dev dependencies
        run: |
          python -m pip install --upgrade pip
          # Hatch & Hatchling for editable install
          pip install hatch hatchling
          pip install -e ".[dev]"

      - name: Run test suite
        run: |
          pytest --color=yes --cov=mapper --cov-report=xml

      - name: Upload coverage to Codecov
        if: runner.os == 'Linux' && matrix.python-version == '3.12'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true
