name: Lint

on:
  push:
    branches: ['main', 'dev', 'feature/**', 'automations']
  pull_request:
    branches: ['main', 'dev']

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install pre‑commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre‑commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
